### ISSUE TITLE
Some simple questions about the symmetry operation matrix

### ISSUE THREAD

**Issue by HegemonyTao** [lrcfmd/ipcsp#1]
Hi, I've read your wonderful paper in **Nature**, it's a real masterpiece. But when I read your code, I can't figure out how you generate the symmetry matrix (as show in below). I tried using **Pyxtal** and **Pymatgen** to generate rotation and translation matrices, but the results were different from yours. Therefore, can you tell me how to generate a symmetric operation matrix used in your paper under a specific space group (eg. 195) . This will help me a lot !!!

This is the symmetry matrix where the space group number is 195 in your code, how to generate it ?
```
1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1
0,0,1,0, 1,0,0,0, 0,1,0,0, 0,0,0,1
0,1,0,0, 0,0,1,0, 1,0,0,0, 0,0,0,1
0,-1,0,0, 0,0,-1,0, 1,0,0,0, 0,0,0,1
0,0,1,0, -1,0,0,0, 0,-1,0,0, 0,0,0,1
0,-1,0,0, 0,0,1,0, -1,0,0,0, 0,0,0,1
0,0,-1,0, -1,0,0,0, 0,1,0,0, 0,0,0,1
0,0,-1,0, 1,0,0,0, 0,-1,0,0, 0,0,0,1
0,1,0,0, 0,0,-1,0, -1,0,0,0, 0,0,0,1
-1,0,0,0, 0,-1,0,0, 0,0,1,0, 0,0,0,1
1,0,0,0, 0,-1,0,0, 0,0,-1,0, 0,0,0,1
-1,0,0,0, 0,1,0,0, 0,0,-1,0, 0,0,0,1
```

**Comment by vlgusev** [comment]
I am really glad that you enjoyed our work. Indeed, that's a research code, so not all details are documented. Refactoring is in progress, but no estimates.

There are two options for you to proceed.

Option A: you can avoid messing with this issue by creating your own files in data/grids. C{g}.txt lists fractional coordinates of all positions in order. CO{g}G{space group}.json simply says which of them should be equivalent under the action of a given group. Since you are already using the other packages, it might be the fastest option.

Option B: I have used [sginfo](https://cci.lbl.gov/sginfo/) with -Maple option. It should give more or less the same answer. This notation comes from Section 8.1.2 by Wondratschek from the International Tables for Crystallography. However, beware, that the parser in readGroup() is limited in functionality, so might not be able to read all the groups. Thus, generate_cubic_orbits(), which is used to create CO{g}G{space group}.json might have issues too.

**Comment by HegemonyTao** [comment]
Thank you for your answer. I will try it out later.
